# Generated by Django 6.0 on 2025-12-31 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('slide_count', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='branding/profiles/')),
                ('profile_handle', models.CharField(blank=True, help_text='Social media handle for @ symbol', max_length=100, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('extra_text', models.TextField(blank=True, help_text='Additional custom text for the slide', null=True)),
                ('image_prompt', models.TextField()),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('font_color', models.CharField(default='#000000', max_length=20)),
                ('saystorys_width', models.IntegerField(default=1080)),
                ('saystorys_height', models.IntegerField(default=1080)),
                ('title_x', models.IntegerField(blank=True, null=True)),
                ('title_y', models.IntegerField(blank=True, null=True)),
                ('description_x', models.IntegerField(blank=True, null=True)),
                ('description_y', models.IntegerField(blank=True, null=True)),
                ('extra_text_x', models.IntegerField(blank=True, null=True)),
                ('extra_text_y', models.IntegerField(blank=True, null=True)),
                ('text_styles', models.TextField(blank=True, default='{}')),
                ('extra_texts', models.TextField(blank=True, default='[]')),
                ('user_images', models.TextField(blank=True, default='[]')),
                ('generated_image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.carouselproject')),
            ],
            options={
                'ordering': ['slide_number'],
            },
        ),
    ]
