# Generated by Django 6.0 on 2026-01-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('business', 'Business'), ('technology', 'Technology'), ('health', 'Health & Fitness'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('creative', 'Creative'), ('travel', 'Travel'), ('finance', 'Finance'), ('fashion', 'Fashion'), ('food', 'Food')], max_length=50)),
                ('platform', models.CharField(default='instagram', max_length=50)),
                ('style', models.CharField(default='modern', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.TextField(blank=True)),
                ('slide_images', models.TextField(default='[]')),
                ('slide_count', models.IntegerField(default=5)),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('secondary_color', models.CharField(default='#F5F5F5', max_length=20)),
                ('accent_color', models.CharField(default='#3B82F6', max_length=20)),
                ('font_color', models.CharField(default='#1F2937', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
