# Generated by Django 6.0 on 2026-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carouseltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='layout',
            field=models.CharField(choices=[('image-top', 'Image Top, Text Below'), ('image-left', 'Image Left, Text Right'), ('image-right', 'Image Right, Text Left'), ('full-background', 'Full Background Image')], default='full-background', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('variant_number', models.IntegerField()),
                ('variant_name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('slide_count', models.IntegerField()),
                ('slides_json', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['variant_number'],
                'unique_together': {('session_id', 'variant_number')},
            },
        ),
    ]
