# Generated by Django 4.2.27 on 2025-12-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carouselproject_profile_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='canvas_height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='slide',
            name='canvas_width',
            field=models.IntegerField(default=1080),
        ),
    ]
