# Generated by Django 6.0 on 2025-12-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_canvas_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='extra_text',
            field=models.TextField(blank=True, help_text='Additional custom text for the slide', null=True),
        ),
    ]
