# Generated by Django 4.2.27 on 2025-12-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_slide_extra_text'),
    ]

    operations = [
    ]
