# Generated by Django 6.0 on 2025-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20251227_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='extra_text_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='extra_text_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
