# Generated by Django 6.0 on 2025-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_slide_description_x_slide_description_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselproject',
            name='brand_logo_data',
            field=models.TextField(blank=True, help_text='Base64 encoded brand logo', null=True),
        ),
        migrations.AddField(
            model_name='carouselproject',
            name='profile_image_data',
            field=models.TextField(blank=True, help_text='Base64 encoded profile image', null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='generated_image_data',
            field=models.TextField(blank=True, help_text='Base64 encoded generated image', null=True),
        ),
    ]
