# Generated by Django 6.0 on 2025-12-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_carouselproject_brand_logo_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselproject',
            name='brand_logo_data',
        ),
        migrations.RemoveField(
            model_name='carouselproject',
            name='profile_image_data',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='generated_image_data',
        ),
        migrations.AddField(
            model_name='slide',
            name='text_styles',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
