# Generated by Django 6.0 on 2025-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_carouselproject_brand_logo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='extra_texts',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
