# Generated by Django 6.0 on 2025-12-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_slide_extra_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='user_images',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
